### ISSUE TITLE
Build workflow does not automatically trigger GitHub Pages rebuild

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#166]

**Comment by mara004** [comment]
Still not fixed despite various attempts (see the log). I don't get GH Actions.

**Comment by mara004** [comment]
Hmm, I think the reason why bot commits don't trigger the GH pages workflow is a GH actions safety measure to prevent infinite loops with 2 workflows re-triggering each other.

Yet there should be some way to run this as nested workflow. I'm not sure why the previous approach didn't work, but also don't remember exactly the context what I tried by then anymore.

**Comment by mara004** [comment]
Also not sure why the `workflow_run` approach in `gh_pages.yaml` didn't work:
```yaml
  workflow_run:
    # (well, actually it should only run if ${{ inputs.publish }} is set...)
    workflows: ['Build Packages']
    types: [completed]
```
